
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Mar 17 21:20:13 CST 2020
//----------------------------------------------------

package grammar.ascendent.Sintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NT_TIMES = 34;
  public static final int NT_ARROW = 52;
  public static final int NT_FUNCTION = 21;
  public static final int NT_COLON = 48;
  public static final int NT_TRUE = 6;
  public static final int NT_DO = 14;
  public static final int NT_WHILE = 13;
  public static final int NT_O_PARENTHESES = 26;
  public static final int NT_NULL = 16;
  public static final int NT_UMINUS = 33;
  public static final int NT_CONTINUE = 19;
  public static final int NT_DEFAULT = 12;
  public static final int NT_DOUBLE = 4;
  public static final int NT_ELSE = 9;
  public static final int NT_FALSE = 7;
  public static final int NT_O_CROTCHES = 24;
  public static final int NT_LESSQ = 39;
  public static final int NT_POT = 37;
  public static final int NT_JUMPLINE = 51;
  public static final int NT_DBC_CROTCHES = 23;
  public static final int NT_GREATERQ = 41;
  public static final int NT_ASSIGN = 46;
  public static final int NT_OR = 45;
  public static final int EOF = 0;
  public static final int NT_IN = 17;
  public static final int NT_FOR = 15;
  public static final int error = 1;
  public static final int NT_O_BRACES = 28;
  public static final int NT_AND = 44;
  public static final int NT_NOT = 30;
  public static final int NT_IF = 8;
  public static final int NT_DIVIDED = 35;
  public static final int NT_GREATER = 40;
  public static final int NT_MINUS = 32;
  public static final int NT_ID = 5;
  public static final int NT_NOT_EQUAL = 43;
  public static final int NT_C_BRACES = 29;
  public static final int NT_NUMBER = 3;
  public static final int NT_C_QUESTION = 47;
  public static final int NT_SWITCH = 10;
  public static final int NT_COMMA = 50;
  public static final int NT_CASE = 11;
  public static final int NT_C_PARENTHESES = 27;
  public static final int NT_SEMICOLON = 49;
  public static final int NT_LESS = 38;
  public static final int NT_C_CROTCHES = 25;
  public static final int NT_EQUAL = 42;
  public static final int NT_MOD = 36;
  public static final int NT_STRING = 2;
  public static final int NT_DBO_CROTCHES = 22;
  public static final int NT_BREAK = 18;
  public static final int NT_return = 20;
  public static final int NT_PLUS = 31;
}

